### ISSUE TITLE
Per-environment configuration

### ISSUE THREAD

**Issue by matthewbdaly** [matthewbdaly/statico#13]
It should be possible to configure most settings on a per-environment basis, eg:

```yml
loggers:
  - dev:
    - logger: stream
      path: ./logs/site.log
  - production:
    - logger: browser-console
```

However, it should still support global settings.
